#ifndef KEA_ENGINE_INCLUDE_ENGINE_MOUSEBUTTONS_HPP
#define KEA_ENGINE_INCLUDE_ENGINE_MOUSEBUTTONS_HPP

#include "glfw/glfw3.h"

namespace Kea
{

enum class MouseButton
{
    MOUSE_1 = GLFW_MOUSE_BUTTON_1,
    MOUSE_2 = GLFW_MOUSE_BUTTON_2,
    MOUSE_3 = GLFW_MOUSE_BUTTON_3,
    MOUSE_4 = GLFW_MOUSE_BUTTON_4,
    MOUSE_5 = GLFW_MOUSE_BUTTON_5,
    MOUSE_6 = GLFW_MOUSE_BUTTON_6,
    MOUSE_7 = GLFW_MOUSE_BUTTON_7,
    MOUSE_8 = GLFW_MOUSE_BUTTON_8,
    MOUSE_LAST = GLFW_MOUSE_BUTTON_LAST,
    MOUSE_LEFT = GLFW_MOUSE_BUTTON_LEFT,
    MOUSE_RIGHT = GLFW_MOUSE_BUTTON_RIGHT,
    MOUSE_MIDDLE = GLFW_MOUSE_BUTTON_MIDDLE,
};

}

#endif /* KEA_ENGINE_INCLUDE_ENGINE_MOUSEBUTTONS_HPP */
